# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goclickup < Formula
  desc "A blazing fast terminal UI for ClickUp."
  homepage "https://github.com/PeterJohnBishop/GoCLIckUp"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PeterJohnBishop/GoCLIckUp/releases/download/v1.0.1/GoCLIckUp_Darwin_x86_64.tar.gz"
      sha256 "5954eb82193b2e9c5384ef2cff619ffcbcf71485385eba466c7fc6b0dcbf7cdb"

      define_method(:install) do
        bin.install "GoCLIckUp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PeterJohnBishop/GoCLIckUp/releases/download/v1.0.1/GoCLIckUp_Darwin_arm64.tar.gz"
      sha256 "9edbdb4be21a1f87e797ae76ce00f815e230269e071accb27aeca23fcdc54456"

      define_method(:install) do
        bin.install "GoCLIckUp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PeterJohnBishop/GoCLIckUp/releases/download/v1.0.1/GoCLIckUp_Linux_x86_64.tar.gz"
      sha256 "6ee057b213e9b52e5ffa30ca871aee8fa4a7e6a1ff25550192048005485d14d5"
      define_method(:install) do
        bin.install "GoCLIckUp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PeterJohnBishop/GoCLIckUp/releases/download/v1.0.1/GoCLIckUp_Linux_arm64.tar.gz"
      sha256 "7130b1eab648bed3eec98f5031159b7541e2ac65df4aa5242224c0f7f21b437b"
      define_method(:install) do
        bin.install "GoCLIckUp"
      end
    end
  end

  test do
    system "#{bin}/goclickup --version"
  end
end
