# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goclicu < Formula
  desc "A blazing fast terminal UI for ClickUp."
  homepage "https://github.com/PeterJohnBishop/goclicu"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.5/goclicu_Darwin_x86_64.tar.gz"
      sha256 "7c9ad829070831c7564eec85b18121acc0ed20b8dcfa60348d65dd36c76243ee"

      define_method(:install) do
        bin.install "goclicu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.5/goclicu_Darwin_arm64.tar.gz"
      sha256 "29ff6b544534129379004132566ea0accbc4f11543a58c2b5ea9661568018699"

      define_method(:install) do
        bin.install "goclicu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.5/goclicu_Linux_x86_64.tar.gz"
      sha256 "cf23ce9943884c97da87606a42ca57567751a818b301462cc4a2af607e51c1fb"
      define_method(:install) do
        bin.install "goclicu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.5/goclicu_Linux_arm64.tar.gz"
      sha256 "5f6a102d49909bd3ec0d06abb4d9626d073e8106301d98232fc7ed7e39eef0fe"
      define_method(:install) do
        bin.install "goclicu"
      end
    end
  end

  test do
    system "#{bin}/goclicu --version"
  end
end
