# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goclicu < Formula
  desc "A blazing fast terminal UI for ClickUp."
  homepage "https://github.com/PeterJohnBishop/goclicu"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.5/goclicu_Darwin_x86_64.tar.gz"
      sha256 "59a4fd64102fa46cacc44aaaf85d40c67527a7be7f247c06edd06824f35addbc"

      define_method(:install) do
        bin.install "goclicu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.5/goclicu_Darwin_arm64.tar.gz"
      sha256 "c9058642f60945d8af06324ba9bd09338548d8d4071be6230615a7ed07078838"

      define_method(:install) do
        bin.install "goclicu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.5/goclicu_Linux_x86_64.tar.gz"
      sha256 "24c58feb8636cb6cd5a6393ac1b3ce8e27756ae6b37f5ae023e673fe0d79cb55"
      define_method(:install) do
        bin.install "goclicu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.5/goclicu_Linux_arm64.tar.gz"
      sha256 "057100c46874283444763ce8146d9e50ba54f31bdfcdee2bb4916209fb88bee0"
      define_method(:install) do
        bin.install "goclicu"
      end
    end
  end

  test do
    system "#{bin}/goclicu --version"
  end
end
